name: pyang (XSD pattern statement)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
          python-version: '3.x'

    - name: Set up pyang
      run: pip3 install pyang

    - name: Run test
      run: pytests/tests/plugin_test.sh

  demo:
    name: Demo
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
          python-version: '3.x'

    - name: Set up pyang
      run: pip3 install pyang

    - name: Get public repo
      run: git clone git@github.com:openconfig/public.git /go/src/github.com/openconfig/public

    - name: Run test
      run: OCDIR=/go/src/github.com/openconfig/public pytests/pattern_test.sh
